<?php

return [
    'marketing.core' => [
        'marketing.view',
        'marketing.dashboard.view',
        'marketing.pipeline.view',
        'marketing.pipeline.manage',
        'marketing.asset.publish',
    ],
    'marketing.customers' => [
        'marketing.customers.view',
        'marketing.customers.create',
        'marketing.customers.update',
        'marketing.customers.delete',
        'marketing.customer.view',
        'marketing.customer.create',
        'marketing.customer.update',
        'marketing.customer.delete',
        'marketing.customer.import',
    ],
    'marketing.contacts' => [
        'marketing.contact.view',
        'marketing.contact.create',
        'marketing.contact.update',
        'marketing.contact.delete',
    ],
    'marketing.addresses' => [
        'marketing.address.view',
        'marketing.address.create',
        'marketing.address.update',
        'marketing.address.delete',
    ],
    'marketing.opportunities' => [
        'marketing.opportunity.view',
        'marketing.opportunity.create',
        'marketing.opportunity.update',
        'marketing.opportunity.delete',
    ],
    'marketing.quotes' => [
        'marketing.quote.view',
        'marketing.quote.create',
        'marketing.quote.update',
        'marketing.quote.delete',
        'marketing.quote.print',
    ],
    'marketing.orders' => [
        'marketing.orders.view',
        'marketing.orders.create',
        'marketing.orders.update',
        'marketing.orders.confirm',
        'marketing.orders.cancel',
        'marketing.order.view',
        'marketing.order.create',
        'marketing.order.update',
        'marketing.order.delete',
        'marketing.order.approve',
        'marketing.order.print',
    ],
    'marketing.pricelists' => [
        'marketing.pricelists.view',
        'marketing.pricelists.create',
        'marketing.pricelists.update',
        'marketing.pricelists.delete',
        'marketing.pricelists.bulk_update',
        'marketing.pricelist.view',
        'marketing.pricelist.create',
        'marketing.pricelist.update',
        'marketing.pricelist.delete',
        'marketing.pricelist.bulk_update',
    ],
    'marketing.activities' => [
        'marketing.activity.view',
        'marketing.activity.create',
        'marketing.activity.update',
        'marketing.activity.delete',
    ],
    'marketing.notes' => [
        'marketing.note.view',
        'marketing.note.create',
        'marketing.note.delete',
    ],
    'marketing.attachments' => [
        'marketing.attachment.view',
        'marketing.attachment.create',
        'marketing.attachment.delete',
    ],
    'marketing.returns' => [
        'marketing.returns.view',
        'marketing.returns.create',
        'marketing.returns.approve',
        'marketing.returns.close',
        'marketing.return.view',
        'marketing.return.create',
        'marketing.return.approve',
        'marketing.return.close',
    ],
];
