<?php

return [
    'map' => [
        'marketing' => [
            'marketing.view',
            'marketing.dashboard.view',
            'marketing.pipeline.view',
            'marketing.pipeline.manage',
            'marketing.customer.view',
            'marketing.customer.create',
            'marketing.customer.update',
            'marketing.customer.delete',
            'marketing.customer.import',
            'marketing.contact.view',
            'marketing.contact.create',
            'marketing.contact.update',
            'marketing.contact.delete',
            'marketing.address.view',
            'marketing.address.create',
            'marketing.address.update',
            'marketing.address.delete',
            'marketing.opportunity.view',
            'marketing.opportunity.create',
            'marketing.opportunity.update',
            'marketing.opportunity.delete',
            'marketing.quote.view',
            'marketing.quote.create',
            'marketing.quote.update',
            'marketing.quote.delete',
            'marketing.quote.print',
            'marketing.order.view',
            'marketing.order.create',
            'marketing.order.update',
            'marketing.order.delete',
            'marketing.order.approve',
            'marketing.order.print',
            'marketing.activity.view',
            'marketing.activity.create',
            'marketing.activity.update',
            'marketing.activity.delete',
            'marketing.note.view',
            'marketing.note.create',
            'marketing.note.delete',
            'marketing.attachment.view',
            'marketing.attachment.create',
            'marketing.attachment.delete',
        ],
        'inventory' => [
            'inventory.view',
            'inventory.product.create',
            'inventory.product.update',
            'inventory.product.delete',
            'inventory.stock.adjust',
        ],
        'procurement' => [
            'procurement.view',
            'procurement.order.create',
            'procurement.order.update',
            'procurement.order.delete',
            'procurement.invoice.approve',
        ],
        'logistics' => [
            'logistics.view',
            'logistics.shipment.create',
            'logistics.shipment.update',
            'logistics.shipment.delete',
        ],
        'production' => [
            'production.view',
            'production.workorder.create',
            'production.workorder.update',
            'production.workorder.delete',
        ],
        'finance' => [
            'finance.view',
            'finance.invoice.post',
            'finance.payment.register',
            'finance.reports.view',
        ],
        'drive' => [
            'drive.view',
            'drive.media.upload',
            'drive.media.delete',
        ],
        'cms' => [
            'cms.manage',
        ],
        'settings' => [
            'settings.view',
            'settings.user.manage',
            'settings.company.update',
        ],
    ],
];
